### ISSUE TITLE
Upgrade golang watch tool

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#115]
For a while we had other solution working, but it went obsolete and then we are with stock `go` command now, but live reload is a nice comfort feature.

As a suggestion, I've found this tool to solve the same problem: https://github.com/cosmtrek/air

Modify agent's [Makefile](https://github.com/dyrector-io/dyrectorio/blob/develop/agent/Makefile). The 2 build targets `go-crane` & `go-dagent` are to use the tool above. :ok_hand: 

The issue is done if running the targets above and modifying code results in live-reloading.

**Comment by katarzynakawala** [comment]
Hey, could I work on it?

**Comment by nandor-magyar** [comment]
Yes, feel free to work on it, don't hesitate to ask if you have any questions, you can find us on discord.

**Comment by katarzynakawala** [comment]
Hi, unfortunately, because of my busy schedule I will not be able to solve it, sorry for that. But maybe someone else would like to pick it up

**Comment by nandor-magyar** [comment]
Thanks for the update @katarzynakawala!

**Comment by minhoryang** [comment]
took over.
