### ISSUE TITLE
Use Prisma @updateAt signature instead of manually doing

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#208]
We have a few `updateAt` columns in our database schema. To avoid boilerplate codes Prisma has a sophisticated solution for this particular problem. They made an `@updateAt` signature: _automatically stores the time when a record was last updated. If you do not supply a time yourself, the Prisma Client will automatically set the value for fields with this attribute._

Prisma Reference documentation: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#updatedat

**Comment by Kit-p** [comment]
Hi @polaroi8d, saw your post in Hacktoberfest Discord.
I'm interested in prisma, can I work on this issue?

**Comment by polaroi8d** [comment]
Hello @Kit-p, for sure 👋🏻 If you have any questions hit me up in our [Discord server.](https://discord.gg/FHq3FMKt)
