### ISSUE TITLE
Create UUIDv4 validation for the NodeID config string

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#217]
In `agent/internal/config/config.go` we store our configuration defaults. In `line 28` you can find NodeID which is an UUIDv4 string, but we don't validate it. Please create a validation for this particular data.

If you are ready with the task, please remove the `// TODO` line from the file. 

More info: 
A universally unique identifier (`UUID`) is an identifier standard used in software construction. The meaning of each bit is defined by any of several variants. It is a 128-bit value. Currently, UUID's are as specified in RFC4122. [https://www.rfc-editor.org/rfc/rfc4122#section-4.1.7](https://www.rfc-editor.org/rfc/rfc4122#section-4.1.7)

**Comment by Akshu-on-github** [comment]
Hello there, I'd like to take this issue up

**Comment by polaroi8d** [comment]
@raghav-rama for sure. If you have a question just drop us a message on [Discord](https://discord.gg/FHq3FMKt).

**Comment by raghav-rama** [comment]
To open PR, first I need to be assigned, right?

**Comment by polaroi8d** [comment]
@raghav-rama I am assigned to you.

**Comment by raghav-rama** [comment]
![image](https://user-images.githubusercontent.com/91389059/197160656-87c63653-dbdb-4ef5-ad6f-36259e506842.png)
I've done this much, but I can't understand how you are taking the string as input. Can you explain that @polaroi8d?

**Comment by nandor-magyar** [comment]
It is done by the library we use: cleanenv. You have to create a new type alias, `type UUID string`, then use setValue() function with correct types and parameters. Similar others in the config folder.
See lib docs and examples here too: https://github.com/ilyakaznacheev/cleanenv
