### ISSUE TITLE
Show prefix validation in one line 

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#218]
1. Add a node to your workspace
2. Create a new Product (`simple` product type is good for now)
3. Click the 'Add deployment'
4. Select your Node
5. Fill up the input with `-` and you will see the error. 

Showing an error in the attached picture. 

![image](https://user-images.githubusercontent.com/9247788/193071407-78d7cb94-ced7-4a16-8951-447f2357d7f3.png)

**Comment by FireNdIce3** [comment]
Hi! Can I work on this issue?

**Comment by polaroi8d** [comment]
@FireNdIce3 for sure. If you have a question just drop us a message in [Discord](https://discord.gg/FHq3FMKt).

**Comment by Swap-Nova** [comment]
Hey can you assign this issue to me as no progress is seen by the previous user.

**Comment by polaroi8d** [comment]
@Swap-Nova for sure, there is no progress right now.

**Comment by Swap-Nova** [comment]
Can you tell me how to test the server after making the changes?

**Comment by polaroi8d** [comment]
@Swap-Nova just use our `cli` tool to fire up the whole stack, and you can check at `localhost:3000` if you have any trouble just come to our Discord server and we'll help to resolve your issue.

**Comment by Swap-Nova** [comment]
Okay sure. Will send a PR soon

**Comment by Swap-Nova** [comment]
@polaroi8d Can you share the 'command' to fire up the whole stack and test the server.

**Comment by polaroi8d** [comment]
> @polaroi8d Can you share the 'command' to fire up the whole stack and test the server.

Just use `make up` in the root folder.

**Comment by polaroi8d** [comment]
Stale.
