### ISSUE TITLE
Upgrade Prisma Client to 4.4.0

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#219]
As the title says upgrade the Prisma package in `web/crux` service.

**Comment by Panda-Abhisek** [comment]
I am a beginner at contributing.
Can you guide me in this?

**Comment by polaroi8d** [comment]
Sorry @Panda-Abhisek but it's already done by Kit. Reference: Reference #226

**Comment by Panda-Abhisek** [comment]
OK
