### ISSUE TITLE
Add new docker container builder attribute: shell

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#220]
https://github.com/dyrector-io/dyrectorio/tree/develop/agent/pkg/builder/container

We have a general purpose container builder.
One can already set `CMD`, `ENTRYPOINT` (and many other things), but `SHELL` is not on option list yet.

TODO: extend the contianer builder interface and the implementation with a new `WithShell` function, similar to the functions already present in the builder. Use the reference linked below.

https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate

The issue is complete if the WithShell function is there, and there are tests verifying its basic use case.
Note: for a unit test it is sufficient to check if the value is really set, for an integration test one has to inspect the started container if its shell is changed.

**Comment by raghav-rama** [comment]
I want to work on this under Hacktoberfest '22

**Comment by polaroi8d** [comment]
@raghav-rama for sure. If you have any questions just drop us a message on [Discord](https://discord.gg/FHq3FMKt).

**Comment by polaroi8d** [comment]
> I want to work on this under Hacktoberfest '22

Any update @raghav-rama?

**Comment by raghav-rama** [comment]
Can you please give me a little more time....

**Comment by raghav-rama** [comment]
I'm still figuring out things

**Comment by polaroi8d** [comment]
@raghav-rama no worries, take your time. I want to let you know if you have any problem or question you could find us on our [Discord](https://discord.gg/n5ASdrz3pZ)
