### ISSUE TITLE
Add new builder: container exec

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#221]
Based on our container [builder](https://github.com/dyrector-io/dyrectorio/tree/develop/agent/pkg/builder/container)

TODO: Add a new builder named ExecBuilder, into the same package into a file `exec_builder.go`.

The builder should be created new a NewExecBuilder(containerID string) function.
Use the builder to set any given parameter and .Start() should return the output / result of the executed command.

Use the API as a reference.
https://docs.docker.com/engine/api/v1.41/#tag/Exec/operation/ContainerExec

Golang package:
https://pkg.go.dev/github.com/docker/docker/client#Client.ContainerExecCreate

**Comment by PankhudiB** [comment]
Can I work on this issue under Hacktoberfest '22 ?
