### ISSUE TITLE
Add target x64 install to package.json

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#224]
We are using `grpc-node` and they don't have a precompiled ARM binary. So if you are trying to install the `crux-ui` component from the code repository, you have to add a `--target_arch=x64` flag. Please create a new install script eg.: `install:x64` with the mentioned flag. 

`package.json` location: `web/crux-ui/package.json` 

Information about the issue and the solution: https://github.com/grpc/grpc-node/issues/1405

**Comment by princefishthrower** [comment]
@polaroi8d I can take this!

**Comment by polaroi8d** [comment]
Linked PR #227
