### ISSUE TITLE
Prisma database seeder data is outdated 

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#232]
At present the Google Demo example seed not working. Please extend the seeder with the necessary code. You have to edit only the `web/crux/prisma/seeds/demo-seeder.ts` file. When you are ready please rename the file to `microservice-seeder.ts`.

Steps to reproduce: 
1. Setup dyrector.io platform
2. Create a User and log in
3. After the first login create a Team
4. Check the `UsersOnTeams` table for `userId` and `teamId`
5. Run the [Google Microservice example](https://github.com/GoogleCloudPlatform/microservices-demo) seeder in `web/crux` folder with the following command: `npm run seed:microservice` 

```
PrismaClientValidationError: 
Invalid `prisma.image.create()` invocation in
/Users/orbanl/Work/dyrector.io/repos/dyrectorio/web/crux/prisma/seeds/demo-seeder.ts:55:40
```

**Comment by polaroi8d** [comment]
@Kirito64 go ahead, feel free to work on it, don't hesitate to ask if you have any questions, you can find us on [Discord](https://discord.gg/n5ASdrz3pZ).

**Comment by Kirito64** [comment]
Yes sure

**Comment by polaroi8d** [comment]
Outdated. We removed the database seeder. You could use templates to seed your platform with mock data.
