### ISSUE TITLE
Implement Mattermost Webhook in Notifications

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#233]
At present we have Discord, Slack & Team integration with webhooks. Please implement Mattermost Webhooks next to the existing ones. 

You have to work around the `web/crux/src/app/notification` for the backend and `web/crux-ui/src/components/notification` for the user interface. Furthermore, you have to extend the `protobuff` file with the new `NotificationType`.

Add regexp to check the validation of the webhook URL. 

Mattermost Webhook Documentation: https://developers.mattermost.com/integrate/webhooks/incoming/

**Comment by bpvcode** [comment]
Hello :)

Can I work on this issue?

I never implemented this and looks like a good challenge. :)

But i probably need more information on your side:

- What is you mattermost server?
- Do you have incoming webhooks enabled?
- Do you have secrets to store sensitive information?

Thanks :)

**Comment by polaroi8d** [comment]
Hi @bpvcode go ahead, feel free to work on it, don't hesitate to ask if you have any questions, you can find us on [Discord](https://discord.gg/n5ASdrz3pZ).

Here is our demo server, with enabled webhooks. Link: https://dyrectorio.cloud.mattermost.com/

**Comment by asi309** [comment]
Hi,
Is this issue still open? If so please assign it to me
