### ISSUE TITLE
Add docker/agent ability to check the given CRI socket 

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#236]
You can install dyrectorio agent whether you are using Kubernetes or Docker. In a Docker way, we can't assume you are using Docker on Linux, because there are other container runtimes like Podman or other platforms like Windows. 

At present you can pass this options in `hostDockerSockPath` at `agent/pkg/dagent/config/config.go:16`, but the parsing and checks are missing. If the env is missing please add a default with `cleanenv` which can be computed at runtime since we currently assume a static default, other hand If the user is provided some path please check the socket. 

_If the value is empty you can calculate it from `DOCKER_HOST` variable using URL parsing from the official go package,  if the `DOCKER_HOST` variable is empty as well please use the Docker SDK's default (platform-specific) socket value._

**Comment by c3ppc3pp** [comment]
Was fixed in #299
