### ISSUE TITLE
Write unit tests for agent and we'll send you an awesome dyrectorio swag cap

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#241]
Right now `/agent` service code coverage is around 8.67% - at events such as Hacktoberfest, it's a good first issue to write unit tests around the code base. You can add tests to `/cli` if you're a black belt unit test writer.

We know unit test writing isn't the most exciting task, so we'd like to motivate our contributors. So if you add more than 10% coverage in the golang side of the repository, we'll send you an awesome dyrectorio swag cap. 

You can find codecov agent/ coverage: https://app.codecov.io/gh/dyrector-io/dyrectorio/blob/develop/agent/pkg/builder/container/types.go

**Comment by clebs** [comment]
Hi @polaroi8d,
I find the project quite interesting and can write some unit tests for the agent.

**Comment by clebs** [comment]
Hi @polaroi8d,
I tested the first pkg on the agent. I will test more packages when I have time but will always send PRs with one pkg each to not overwhelm the reviewers.

Looking forward to your feedback.

**Comment by polaroi8d** [comment]
> Hi @polaroi8d, I tested the first pkg on the agent. I will test more packages when I have time but will always send PRs with one pkg each to not overwhelm the reviewers.
> 
> Looking forward to your feedback.

Good strategy, thanks! :)))

**Comment by joremysh** [comment]
I could help with adding the unit tests. Is this issue still open?

**Comment by polaroi8d** [comment]
@joremysh yea sure, thanks 🤚🏻

**Comment by Dinoosawruss** [comment]
Happy to add some tests if still needed?

**Comment by polaroi8d** [comment]
@Dinoosawruss go ahead!

**Comment by Fall1ngStar** [comment]
👋 I'll add some tests !

**Comment by polaroi8d** [comment]
@Fall1ngStar awesome!

**Comment by SilverTux** [comment]
Hi,

I've created some tests for crane/k8s/error.go as I saw nobody worked on that part before. If there is something wrong with it please let me know and I'll update the PR accordingly.

**Comment by joremysh** [comment]
I'm going to check with `agent/internal/crypt` first.

**Comment by clebs** [comment]
I am testing `agent/internal/mapper` next!

**Comment by clebs** [comment]
Hi @nandor-magyar I added a PR for the mapper that was previously on the agent. I saw it moved to `golang/internal` while I was implementing the tests.

I hope it is still fine.

**Comment by polaroi8d** [comment]
Ofc @clebs we'll review it. Otherhand could you drop me an email at levente.orban[at]dyrector[dot]io ?

**Comment by clebs** [comment]
Great thank you! Will send you an email as well.
