### ISSUE TITLE
Refactor: k8s-agent private-key init: generate

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#244]
The original task is split into two, this is the first half.
It might seem difficult, it covers a lot, but the issue is explicit.

You are going to need a cluster to develop this feature & test it, that can be done locally: kind or minikube.

Issue:
Right now **crane** (that is the in-house name of our k8s agent) deployment is depending on having a persistent volume attach to store its private key that is used for secret encryption. Attaching a PVC imposes heavy restrictions and possible configuration problems possibly leading to inconsistent behavior in different environments, while using kubernetes native objects can already save the day.

Folder of k8s manifests:
https://github.com/dyrector-io/dyrectorio/tree/develop/agent/manifest/kubernetes

Currently the private key that is generated is written to a file.

TODO:
1. Extend crane with a CLI command as an option to run `crane init`,  if nothing is provided start the program normally
2. Add new makefile (agent/Makefile) target: go-crane-init
  - it starts the init process, then exit
3. The init function can use the `generateKey` function to generate the key (internal/config/secret.go) - expose it
4. Save the output to a k8s opaque secret 
5. Reorganize configurations
  - Move the current secret behavior (type `ConfigFromFile`) into pkg/dagent/config/secret.go package and into dagent's own config type
  - Create new type in a similar way for achieving similar effects using secrets into crane `ConfigFromSecret` pkg/crane/config/secret.go
  - The new type setter in crane expects a string (namespace), from env variable: NAMESPACE - also new.
  - In the setter
    - If namespace not provided, attempt to use the `dyrectorio` namespace
    - GetSecretClient function can be reused from k8s package - expose it
    - Load secret value

Hint:
Avoid panics, make sure to run lint, unit tests are welcome.

**Comment by minhoryang** [comment]
Hello @nandor-magyar , I'm interested in this issue.

During the initial investigation of below todo, I have no idea that how to save the output from initContainer's stdout to k8s opaque secret in yaml form. 
> 4. Save the output to a k8s opaque secret 

Do I need to store it directly through the Kube API? or Call `kubectl create` on `Makefile`?

**Comment by minhoryang** [comment]
> The new type setter in crane expects a string (namespace), from env variable: NAMESPACE - also new.

Oh, maybe I need to implement it as first way ("directly through the Kube API" in crane itself.)

**Comment by nandor-magyar** [comment]
Correct. You can use crane's functions, though I would assume you won't need much of the code, only a secret client that is mentioned in the issue.

**Comment by minhoryang** [comment]
This is my first attempt of using a golang on production. so my question would be quite silly for maintainers.

I'm getting a circular import error between `agent/pkg/crane/config/secret.go` and `agent/pkg/crane/k8s/secret.go` during 
> - Create new type in a similar way for achieving similar effects using secrets into crane ConfigFromSecret pkg/crane/config/secret.go
> - The new type setter in crane expects a string (namespace), from env variable: NAMESPACE - also new.
> - In the setter
>   - If namespace not provided, attempt to use the dyrectorio namespace
>   - GetSecretClient function can be reused from k8s package - expose it
>   - Load secret value

What about moving all ConfigFromSecret related codes to `agent/cmd/crane/secret.go`?

**Comment by nandor-magyar** [comment]
There is nothing silly about asking questions, the most efficient way would be if you could open a draft PR with the changes you have already.
Moving into the `cmd` directory is not really preferred if it used elsewhere in under pkg, but isolating the common part is the right approach. :+1:
