### ISSUE TITLE
Refactor: k8s-agent deployment update

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#245]
The original task is split into two, this is the second half.
The other part: https://github.com/dyrector-io/dyrectorio/issues/244

You are going to need a cluster to develop this feature & test it, that can be done locally: kind or minikube.

Folder of k8s manifests:
https://github.com/dyrector-io/dyrectorio/tree/develop/agent/manifest/kubernetes

TODO:
- Extend the deployment manifest with an init-container, using the same image, receiving the config map, but having an extra `init` argument
- Test

Using the cli, you can start the application fairly easy and can test if it is working.

Expected behavior:
  - Setup a k8s node in dyrectorio
  - apply your local version  of the updated manifest using kubectl
  - it should start, connect normally
  - create a simple product
  - creating a deployment targeting your node you **can** provide secrets

**Comment by minhoryang** [comment]
I'll dive in this.

**Comment by minhoryang** [comment]
I'll make a PR after #293 merged.

**Comment by minhoryang** [comment]
merged.
