### ISSUE TITLE
Implement WithHosts function in dockerbuilder

### ISSUE THREAD

**Issue by c3ppc3pp** [dyrector-io/dyrectorio#249]
This issue is caused by:  #248

Currently when we create a container using DockerBuilder we can't define additional hosts, but we should be able to.
Implement a function named WithHosts where we expect a string slice/array as Docker SDK does, and we pass this to it. If we leave the function empty, it should use the current hardcoded value as default. You can find more information about this behaviour  in docker cli  as the `--add-host` parameter or in docker-compose the `extra_hosts:` directive in the yaml file. 

If you have any question about this issue feel free to reach out!

**Comment by polaroi8d** [comment]
@himanshu007-creator go ahead, feel free to work on it, don't hesitate to ask if you have any questions, you can find us on [Discord](https://discord.gg/n5ASdrz3pZ).
