### ISSUE TITLE
Refactor error catches 

### ISSUE THREAD

**Issue by polaroi8d** [dyrector-io/dyrectorio#270]
In the code base at present, we are using 3 versions of catching errors. Versions: `catch (e)`, `catch (err)`, `catch (error)`, please refactor the code and use only one of them.

Affected folders: 
- `web/crux` - NextJS
- `web/crux-ui` - NestJS

**Comment by plopez26DPU** [comment]
Still need help on this?

**Comment by polaroi8d** [comment]
> Still need help on this?

No, thanks @oriapp working on this, anyway thanks.
