### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by HridoyHazard** [dyrector-io/dyrectorio#279]
i would like to improve the readme by adding contributors profile in readme
assign this task to me.i can do it flawlessly

**Comment by c3ppc3pp** [comment]
We appreciate you want to help us, but currently we don't see any value in these kind of contributions as we'd like to keep our README.md for more useful information. GitHub also includes a contributors page on the sidebar we don't have to update manually. 

See here: the contributors page https://github.com/dyrector-io/dyrectorio/graphs/contributors and also a similar issue #258
