### ISSUE TITLE
Resolve "IDP" in project description

### ISSUE THREAD

**Issue by vdavid** [dyrector-io/dyrectorio#318]
Current about is: "Open-source IDP for developers and non-specialists to manage multi-instance deployments, microservices and configurations in Kubernetes & Docker."
I'm a staff-level engineer, but don't know the resolution of "IDP". (best guess: "Integrated Deployment Platform"?) Google didn't help me, [Wikipedia](https://en.wikipedia.org/wiki/IDP) didn't help me, either.
If we strongly believe this is a common abbreviation, I suggest we add it to the Wikipedia page.
Otherwise, I suggest we clearly introduce the term at its first use on the page.

I'd create a PR for this, but:
1. I don't know the resolution of the term
2. I don't think I have permission to set the "About" part of the GitHub project, so this would need contribution from an admin, anyway.

Any thoughts?

**Comment by polaroi8d** [comment]
Yea, we're always struggling to make the best value proposition for the platform. New contributors with out-of-the-box ideas are always welcome. We are using the Humanitec approach: https://internaldeveloperplatform.org/what-is-an-internal-developer-platform/

Anyway thanks for your thought, we'll approve your PR.

**Comment by polaroi8d** [comment]
Fixed the About regarding the changes, cc. @vdavid. Thanks again for the contribution.
