### ISSUE TITLE
problem with postfix

### ISSUE THREAD

**Issue by AmsellemJoseph** [dyrector-io/dyrectorio#545]
Hey,
I am deploying dyrectorio with docker-compose, everything is going well, but when registering I do not receive an email.

I have put an address in the environment variables.

FROM_EMAIL=my@mail.com
SMTP_URI=smtp://172.17.0.1:25/?skip_ssl_verify=true&legacy_ssl=false&smtp_ssl_enabled=false&disable_starttls=true

but in the logs, I repeatedly receive an error from kratos:
msg=Unable to send email using SMTP connection. audience=application error=map[message:gomail: could not send email 1: 554 5.7.1 <mymail@gmail.com>: Recipient address rejected: Access denied] message_from=noreply@dyrector.io service_name=Ory Kratos service_version=v0 .11.0 smtp_server=172.17.0.1:25 smtp_ssl_enabled=false

I use postfix, do you have any idea?
Thanks a lot!!

**Comment by c3ppc3pp** [comment]
Hi!

The `Recipient address rejected: Access denied` error can be caused by a lot of things. As the error indicates it's possible you cannot send to that address but there can be other issues as well.

Is your postfix routing other kind of mails correctly? Do you try to send these mails through the public internet? How does your mailing setup look like?

**Comment by AmsellemJoseph** [comment]
Hey @c3ppc3pp , I'm using a third party SMTP provider

The issue here is I'm configuring [Dyrector.io](http://dyrector.io/) to use a specific SEND FROM email address, but it's still using the hardcoded [noreply@dyrector.io](mailto:noreply@dyrector.io) which of course is REJECTED by my SMTP provider that expect me to send from an allowed address on my domain

So my question is why is the setting above not working? Is there another / newer way to declare the SEND FROM email address to be used instead of the hardcoded [noreply@dyrector.io](mailto:noreply@dyrector.io)?

thx for your help.

**Comment by axlroden** [comment]
same issue..

**Comment by m8vago** [comment]
Hi Guys!

Thank you for reporting the error.
@nandor-magyar found the problem, and he will open a pull request soon with the fix.
