### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by tboulogne** [dyrector-io/dyrectorio#799]
Hello 

i discover dyrectorio with pleasure. Don’t try yet. Does a feature to backup database scheduled ? (Sorry did not see this).

Currently using easypanel and need a manager with an API like dyrectorio.

thanks for answer.

regards

**Comment by polaroi8d** [comment]
Hi @tboulogne 👋🏻 

If I understand correctly, you would like something that allows you to initiate a database that backs up for you at specified intervals?

For now, unfortunately, there is no such feature on the platform, but we would like to develop something similar. However, we are focusing on many other things, so I can't exactly say when we will schedule it.

**Comment by tboulogne** [comment]
>
> If I understand correctly, you would like something that allows you to initiate a database that backs up for you at specified intervals?
@polaroi8d thanks for replying 😎

your understanding is good : could consider database as service with a backup  attached. 

I will try with an external tools with exposed port.

**Comment by polaroi8d** [comment]
@tboulogne it could be a solution for you right now. I found this project: [https://github.com/tiredofit/docker-db-backup](https://github.com/tiredofit/docker-db-backup) - it seems like this project is solving your problem.

**Comment by tboulogne** [comment]
Thanks 😊 I will look into this.Thierry BOULOGNE06 43 18 31 19Le 28 août 2023 à 15:07, Levente Orban ***@***.***> a écrit :﻿
@tboulogne it could be a solution for you right now. I found this project: https://github.com/tiredofit/docker-db-backup - it seems like this project is solving your problem.
