### ISSUE TITLE
Review README.mds

### ISSUE THREAD

**Issue by gerimate** [dyrector-io/dyrectorio#827]
We need assistance in reviewing and improving the following documentation files within our project:

```
- README.md
- CONTRIBUTING.md
- golang/README.md
- web/crux/README.md
- web/crux-ui/README.md
- golang/pkg/crane/README.md
- golang/pkg/crane/README.md
```

**Task Description:**
Your task is to thoroughly review the content of these files. Specifically, we need you to check for the following:

**Readability:** Ensure that the content is easy to understand and navigate for both new and experienced users.

**Validity:** Verify that the documentation accurately reflects the behavior and functionality of the software stack.

**Consistency:** Ensure that the content in these files is consistent with other documents and adheres to our project's established style and formatting guidelines.

**Grammar:** Correct any grammatical errors or typos to maintain a professional and polished appearance.

**Definition of Done:**

Open a pull request for each of the files listed above. If you believe a file requires no changes, please leave a message on our Discord help channel to communicate this.
Your contributions to enhancing the quality and accessibility of our project documentation are greatly appreciated. If you have any questions or need clarification on specific tasks, feel free to ask for assistance. Thank you for your valuable help!

**Comment by polaroi8d** [comment]
As you can see these are non-coding tasks and we'll close this issue after #Hacktoberfest.

**Comment by outlivo** [comment]
Can this be assigned to me?

**Comment by nandor-magyar** [comment]
Hey @outlivo, welcome! Of course.

**Comment by polaroi8d** [comment]
Hi @outlivo, this is not a one-person task. We would appreciate it if you could find someone to help and fix it. However, if others are still willing to review those READMEs, we are open to more suggestions.

**Comment by GuptaPratik02** [comment]
Hi @polaroi8d, I have gone through the readme and contributing file, have improved it and raised PR for that.
Can you review and approve the same.
Thank you.

**Comment by harshsinghcs** [comment]
kindly assign to me.

**Comment by nikita812** [comment]
Hello, 
I too would like to contribute to this, can this be assigned to me
