### ISSUE TITLE
Refactor agent image url parse helper unit tests

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#832]
We have unit tests spread across various functions, but some/most of them could be organized into table driven test cases.

Refactor the tests into table driven ones where it is applicable in the file:
`golang/internal/helper/image/image_unit_test.go`

An example could be seen in `golang/internal/runtime/container/container_test.go` function `TestVersionCheck`.

**Comment by PapePathe** [comment]
Hello can i self assign this issue ?

**Comment by polaroi8d** [comment]
Hi @PapePathe for sure. If you have any questions please ask us. I've assigned the issue to you.

**Comment by PapePathe** [comment]
Hello @polaroi8d i just opened a PR. Let me know how you feel about it.
