### ISSUE TITLE
Fix Broken Logo link in Readme

### ISSUE THREAD

**Issue by mathanraj0601** [dyrector-io/dyrectorio#834]
## Broken logo link
- The Link for the logo is broken in the readme file
![image](https://github.com/dyrector-io/dyrectorio/assets/98396468/b8c82bfc-1960-4d18-b19b-0321415d4580)

**Comment by mathanraj0601** [comment]
I like to work on this. Can you assign it to me?

**Comment by nandor-magyar** [comment]
First, It would be better to know what have gone wrong. It works on most our machines. Is there any error on the developer console?

**Comment by mathanraj0601** [comment]
Hi @nandor-magyar  , I came across this Github repo from Discord for Hacktoberfest. I found that the logo is not visible to me. I cross-checked with my friend's machine. They also can't able to see the logo. I cloned the repo and opened the readme in VS code previewer it works fine and now researching why we can't able to see the logo in the GitHub readme

**Comment by AmorfEvo** [comment]
Thank you for researching this issue, we are also curious, so if you find out the reason let us know.

I also checked at home on Manjaro and on Win10 in different browsers, but it seems fine here (even with dark and light mode).
There are some text wrapping and tag position differences, but they are basically the same.

Vivaldi_Win10
![Vivaldi_Win10](https://github.com/dyrector-io/dyrectorio/assets/7864574/ee79f59e-42ef-437c-8d76-06c01a5d94a9)

Firefox_Win10
![Firefox_Win10](https://github.com/dyrector-io/dyrectorio/assets/7864574/f97ca66a-9bea-48af-89c3-efbcd614bca8)

Brave_Win10
![Brave_Win10](https://github.com/dyrector-io/dyrectorio/assets/7864574/32bc8ecb-4b48-457a-8a7e-aa980d9a4e2a)

Vivaldi_Manjaro
![Vivaldi_Manjaro](https://github.com/dyrector-io/dyrectorio/assets/7864574/600b795b-4565-445f-b955-1cf32e49af84)

Firefox_Manjaro
![Firefox_Manjaro](https://github.com/dyrector-io/dyrectorio/assets/7864574/bbf2e7a5-8410-4769-8490-0d8864f20927)

Brave_Manjaro
![Brave_Manjaro](https://github.com/dyrector-io/dyrectorio/assets/7864574/7aeb6448-29e1-4454-b2f0-9d1064fbce52)

**Comment by AmorfEvo** [comment]
But as you can see on the Firefox_Win10 image, the version tag is only appeared as text first.
When I refreshed the site it showed properly.

Maybe you also experienced this but with the logo.

Firefox_Win10 (2)
![Firefox_Win10_2](https://github.com/dyrector-io/dyrectorio/assets/7864574/6a08a1f0-9fb3-4c06-898b-90195555e10b)

**Comment by mathanraj0601** [comment]
I have viewed the repo using win11_chrome in the laptop meanwhile it working fine in the Mobile there may be some issue in my browser i think so. Thank you for clarifying. If you can once again check in chrome @AmorfEvo

**Comment by AmorfEvo** [comment]
It is fine in Chrome too @mathanraj0601.

Chrome_Win10
![Chrome_Win10](https://github.com/dyrector-io/dyrectorio/assets/7864574/9e31a151-a357-489e-be57-9cfb8b5ecd07)

**Comment by mathanraj0601** [comment]
Okay @AmorfEvo.  there may be issue in my browser. Thank you for clarifying once again you can close the issue : )

**Comment by AmorfEvo** [comment]
All right, I will close this issue @mathanraj0601.
Thanks for reaching out, if you notice any other problem, please let us know and we will look into them :)

**Comment by mathanraj0601** [comment]
Okay, @AmorfEvo. I will look into the project and try to contribute : )

**Comment by polaroi8d** [comment]
@mathanraj0601 It would be great to know why your browser didn't load the header icon. 🤔

**Comment by mathanraj0601** [comment]
hi @polaroi8d, I also don't know why it is not showing 
I attached a screenshot that I took now in a different browser on my device
## win11_chrome
![image](https://github.com/dyrector-io/dyrectorio/assets/98396468/3a4ba3cb-0e17-4ade-9dbe-28696aa92467)
## win11_brave
![image](https://github.com/dyrector-io/dyrectorio/assets/98396468/b09f9d50-570a-4403-9e12-64547f9f02f5)
## win11_edge
![image](https://github.com/dyrector-io/dyrectorio/assets/98396468/45fd7c25-5cc2-44f6-91fb-2af01f57dddd)

Also, I cross-checked with my friend's laptop they are also not able to see the icon

**Comment by robot9706** [comment]
@mathanraj0601 Could you look at the developer consoles of the browsers?

**Comment by mathanraj0601** [comment]
Hi, @robot9706 , GET request for dyrector-dark.png has not received any response but I refreshed for 2-3 times now it fetching the image. Working!!

**Comment by polaroi8d** [comment]
@mathanraj0601 Okey, thanks anyway.
