### ISSUE TITLE
replace the twitter old logo

### ISSUE THREAD

**Issue by chaursiyasanjeet** [dyrector-io/dyrectorio#839]
Hey, I would like to work on replacing the old Twitter logo with new log.
can you please assign me this issue?

**Comment by ayushsgithub** [comment]
Where do you want to change it? @chaursiyasanjeet Please attach a screenshot whenever to you to mention any kind of changes, it would be more easier for others to understand the issue.

**Comment by chaursiyasanjeet** [comment]
### Here
-
<img width="132" alt="image" src="https://github.com/dyrector-io/dyrectorio/assets/111435565/af4a2673-5626-4bc9-b066-1a2161de2191">

**Comment by ayushsgithub** [comment]
Ok, so you want this to be replaced with new "X'' logo? Right?

**Comment by nandor-magyar** [comment]
Hey @chaursiyasanjeet! Thank you for reaching out. Unfortunately the corresponding assets are not in this repository and the other one is not connected to hacktoberfest, also we don't plan to add it.
Thanks again for the notice, closing the issue.

**Comment by chaursiyasanjeet** [comment]
You are welcome @nandor-magyar, if any improvement needed in the frontend then you can reach me
