### ISSUE TITLE
Please prodive multi-arch docker images

### ISSUE THREAD

**Issue by gymnae** [dyrector-io/dyrectorio#842]
I'm trying to run your getting started docker compose, it fails since images are only built for the linux/amd64 platform, but not for linux/arm64:

```
docker pull ghcr.io/dyrector-io/dyrectorio/web/crux:latest
[...]
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
```

Could you adjust your build actions to provide it multiarch? Maybe with buildx.

**Comment by polaroi8d** [comment]
We build our images in multi-arch (personally I'm using the app on my M1 Mac). Did you try to pull with the exact target platform? Eg.: `docker pull --platform linux/arm64 ghcr.io/dyrector-io/dyrectorio/web/crux:latest`

**Comment by polaroi8d** [comment]
Any news on your side @gymnae? Did you try to use the above mentioned command?

**Comment by gymnae** [comment]
> Any news on your side @gymnae? Did you try to use the above mentioned command?

Didn't get to it yet :) What I had tried was to use the provided docker-compose and the CLI getting started script. Botht did not work, as both pulled the x86 images and I cound no way to tell them otherwise. Right now, I'm evaluating another approach for my goal
