### ISSUE TITLE
Docs: Add contributors section in Readme.md

### ISSUE THREAD

**Issue by HeetVekariya** [dyrector-io/dyrectorio#854]
- Currently there is no contributors section in the Readme.md
- I would like a contributors section similar as below:
![image](https://github.com/dyrector-io/dyrectorio/assets/91054457/7193915f-bdfa-41a9-9465-72341016048f)

- If you find this issue valid can you please assign it to me

**Comment by ankitrout2903** [comment]
Can you assign me this issue under hacktoberfest

**Comment by polaroi8d** [comment]
Hi, there is a 'Contribution' section in the right sidebar on the repository GitHub page. We don't want to add this to the readme, based on this I'm closing the issue.
