### ISSUE TITLE
Update Twitter logo to its latest one (X)

### ISSUE THREAD

**Issue by niranjan-kurhade** [dyrector-io/dyrectorio#869]
It's good to stay updated in the tech world.
Hence, update the logo of Twitter to its latest one(X).

Is the code for the website https://dyrectorio.com/ open-source?
if yes, I would like to work on this issue and please assign me!

**Comment by polaroi8d** [comment]
Hi @niranjan-kurhade, yes but not in this repository, this is for the platform. You can find the landing repository in the @dyrector-io organization.
