### ISSUE TITLE
Add show password icon to password input fields

### ISSUE THREAD

**Issue by gerimate** [dyrector-io/dyrectorio#873]
Right now there isn't a show password setting available for the password input fields. There are password input fields in these files:

- github-registry-field.tsx
- gitlab-registry-field.tsx
- v2-registry-field.tsx
- edit-storage-card.tsx
- login.tsx
- register.tsx
- change-password.tsx
- new-password.tsx

Implement a show password option the following way:

The icons used should be these ones:
- When the password is shown, use this icon: https://pictogrammers.com/library/mdi/icon/eye-closed/
- When the password is hidden, use this icon: https://pictogrammers.com/library/mdi/icon/eye-outline/
- The icons should have this color: #d0d2d6

**Comment by chandhuDev** [comment]
Can you assign me?

**Comment by chandhuDev** [comment]
@gerimate I feel it is not the correct icon to show when the password is hidden

**Comment by chandhuDev** [comment]
As it looks like half arc not an eye

**Comment by m8vago** [comment]
implemented by https://github.com/dyrector-io/dyrectorio/pull/887
