### ISSUE TITLE
The URL for the webhook is too strict

### ISSUE THREAD

**Issue by DyllasDek** [dyrector-io/dyrectorio#910]
Our rocket chat has a custom url and because of this it is impossible to connect notifications to the webhook
![image](https://github.com/dyrector-io/dyrectorio/assets/71441017/6e69c861-015c-40d3-9101-d6033ba0ad8d)

**Comment by m8vago** [comment]
Hi @DyllasDek ,

Thank you for opening the issue!

I am going to fix it ASAP.
