### ISSUE TITLE
Troubleshooting the Crux Container Error in Release 0.11.0: Resolving Login Issues in Docker Compose Deployment

### ISSUE THREAD

**Issue by fatm1nd** [dyrector-io/dyrectorio#912]
![image](https://github.com/dyrector-io/dyrectorio/assets/52112937/4c120802-3b6a-470c-acb3-5c8982870dfe)

I have updated to the new release (0.11.0) and am experiencing a problem every time I log in. The logs contain an error in the crux container, as shown in the screenshot. This issue also occurs after I have erased all volumes. I am using docker compose to deploy my containers. All other containers are working fine.

**Comment by nandor-magyar** [comment]
Hey, @fatm1nd! Thank you for reaching out. 

We know about the issue, a small patch is about to be released very soon, addressing this.
The short fix is to provide the environment variable, I assume both crux containers need it.

**Comment by fatm1nd** [comment]
@nandor-magyar You mean give random string value to ENCRYPTION_SECRET_KEY?

**Comment by polaroi8d** [comment]
> @nandor-magyar You mean give random string value to ENCRYPTION_SECRET_KEY?

Yes.
