### ISSUE TITLE
Hardcoded URL in Rocket.Chat notifications

### ISSUE THREAD

**Issue by nandor-magyar** [dyrector-io/dyrectorio#929]
At present, if one uses the Rocket.Chat notifications the URL is hardcoded and points to our landing page. For self-hosted scenarios, this is **not** ideal.

It should at least use the given domain configuration, from the configService.
Also from usability perspective, the message should be extended with a "source-link".
```jsonc
//...
"attachments": [{
   "color": color,
    "fields": [
      {
        "short": true,
        "title": "New Deployment",
        "value": "[Open deployment](" + ${sourceURL} + ")"
      },
//...
```

Related PR: #867

**Comment by polaroi8d** [comment]
PR merged, closing the issue.
