### ISSUE TITLE
Feature idea: Navigate directly from Dashboard

### ISSUE THREAD

**Issue by curtisy1** [dyrector-io/dyrectorio#989]
First off, a big thank you for making dyrector.io!
While playing around with it, I noticed something that would be very handy especially for newcomers like me:
Having shortcuts from the dashboard to the relevant pages in the UI would be a nice little addition.
Currently, I can think of the following

- Users Tile -> User overview for the current team slug (/teams/{uuid})
- Projects Tile -> Project overview for the current team slug (/{slug}/projects)
- Deployments Tile + Failed Deployments Tile -> Deployments overview for the current team slug (/{slug}/deployments)
- Audit Tile -> Audit log overview for the current team slug (/{slug}/audit-log)
- Versions Tile -> Project overview for the current team slug with filter = Versioned set
  I'm unsure about this one but I figured if all other tiles get a redirect, this tile should get one too to avoid confusion 

Let me know what you think. If it's something you can imagine, I'm also open to working on this myself

**Comment by polaroi8d** [comment]
Hey @curtisy1, thanks for the request idea. We talked about something similar internally, but our conclusion was that it might be too complex for the customers. What do you think? Anyway, I love the idea, so if you have time to implement it, we can test it to see how good it is.

**Comment by curtisy1** [comment]
Hey @polaroi8d, I think the complexity would mostly come from users clicking on the link by accident and then think "oh, how did I get here". In most cases, I think it's fine though as they would simply navigate back, hover over one of the tiles and instead think "oh, a shortcut. Nice feature".
This is especially true as most users would be tech-savvy and know how browsers work so they wouldn't get lost by a single misclick (hopefully)

I'll try to spin up a PR in the following days so you can do a round of testing and see how it behaves

**Comment by polaroi8d** [comment]
Hey @curtisy1, is there any update on your side?

**Comment by curtisy1** [comment]
Hey @polaroi8d, sorry for the delay, I've had some personal stuff to do, so I didn't have time to spin up a PR yet. I will hopefully get to it this weekend or early next week

**Comment by polaroi8d** [comment]
> Hey @polaroi8d, sorry for the delay, I've had some personal stuff to do, so I didn't have time to spin up a PR yet. I will hopefully get to it this weekend or early next week

No problem.
